### ISSUE TITLE
请问下关于LT模式的读数据问题

### ISSUE THREAD

**Issue by xiayezhiying** [qinguoyi/TinyWebServer#106]
LT模式下
epoll_wait(m_epollfd, events, MAX_EVENT_NUMBER, -1)
这条语句，有没有可能一个read事件，会在epoll_wait里触发两次？
第一次触发epoll_wait的时候，子线程还未执行到read()函数，之后epoll_wait就触发第二次了

**Comment by Ivringdai** [comment]
LT模式就是多次触发呀：如果socket里面还有数据，下次任然会触发

**Comment by xiayezhiying** [comment]
> LT模式就是多次触发呀：如果socket里面还有数据，下次任然会触发

请问会出现这种情况吗，client发送了一个HTTP request过来。
线程1和线程2都在处理这份HTTP request。
因为它这个epoll_wait里触发了两次，也就在任务队列里添加了两次

**Comment by Ivringdai** [comment]
> > LT模式就是多次触发呀：如果socket里面还有数据，下次任然会触发
> 
> 请问会出现这种情况吗，client发送了一个HTTP request过来。 线程1和线程2都在处理这份HTTP request。 因为它这个epoll_wait里触发了两次，也就在任务队列里添加了两次

对于你说的这个问题，项目中向连接socket注册了EPOLLONESHOT事件，对于注册了该事件的文件描述符，操作系统最多出发其上注册的一个可读、可写或者异常事件，且只触发一次；
具体可参考《linux高性能服务器编程》
