### ISSUE TITLE
dealclinetdata()函数问题

### ISSUE THREAD

**Issue by fengbear** [qinguoyi/TinyWebServer#109]
dealclinetdata()函数里ET模式下，while循环如何退出啊

**Comment by taifuer** [comment]
> dealclinetdata()函数里ET模式下，while循环如何退出啊

当只有一个用户发起请求时，在 ET 模式下，accept接受一个连接后，会再次调用 accept，此时 connfd 会返回 -1 并设置 errno 为 11，表示 Resource temporarily unavailable。
