### ISSUE TITLE
./server可以运行但是网页打不开

### ISSUE THREAD

**Issue by mufeng00** [qinguoyi/TinyWebServer#113]
![微信图片_20220416021548](https://user-images.githubusercontent.com/87609547/163606400-d286cd00-7b09-44d9-afb2-5175e1919123.png)
![微信图片_20220416021631](https://user-images.githubusercontent.com/87609547/163606405-42102a4c-ae77-4dcb-a368-c235e47b1074.png)
mysql版本5.7.37， 有人说改localhost也试了不行。求大佬指导下，快疯了。

**Comment by q1458512338** [comment]
会不会是没有开放端口的问题

**Comment by HUYINHAO999** [comment]
请问解决了吗

**Comment by Delyone** [comment]
请问是怎么解决的呢
