### ISSUE TITLE
外部导入的图片与视频来替换原本的就会无法显示，只有我一个人是这样吗

### ISSUE THREAD

**Issue by q1458512338** [qinguoyi/TinyWebServer#115]
项目内root文件夹本身存在的图片能够被替换并且显示，但我从外部导入的图片与视频就无法显示，请问是哪里出了问题

**Comment by q1458512338** [comment]
我用的是虚拟机，不知道跟这个有没有关系，有大佬遇到过并且解决了的吗，可以指点一下不

> 项目内root文件夹本身存在的图片能够被替换并且显示，但我从外部导入的图片与视频就无法显示，请问是哪里出了问题

**Comment by InternetofThingsprogrammer** [comment]
看不懂你在说啥?root文件夹能换不就是可以换?

**Comment by Nemodontcry** [comment]
修改一下 html
`<div align="center"><img src="./xxx.jpg" title="awsl"/></div>`
原本只有这一行，只请求了这一个图片文件
