### ISSUE TITLE
目前是不支持js+css+html的吗？

### ISSUE THREAD

**Issue by ZYunfeii** [qinguoyi/TinyWebServer#116]
如题，网上下载了一个模板css+js+html，但是在程序中替换后无法在客户端正确打开html。

**Comment by Wangc-fly** [comment]
你好，请问最后解决了吗?可以添加前端页面不

**Comment by ZYunfeii** [comment]
解决了 不过没用这个server了 框架上有小bug 说不上了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinguoyi/TinyWebServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 晚上11:43
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [qinguoyi/TinyWebServer] 目前是不支持js+css+html的吗？ (Issue #116)





 
你好，请问最后解决了吗?可以添加前端页面不

**Comment by Wangc-fly** [comment]
您当时是怎么解决的呀，我这儿加了几个页面浏览器解析不了，一直显示页面的源码。跪求指导。可以的话您能加下我QQ吗，2141916337

**Comment by ZYunfeii** [comment]
这个架构有小问题 我换了cpp11的架构




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinguoyi/TinyWebServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 上午10:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [qinguoyi/TinyWebServer] 目前是不支持js+css+html的吗？ (Issue #116)





 
您当时是怎么解决的呀，我这儿加了几个页面浏览器解析不了，一直显示页面的源码。跪求指导。可以的话您能加下我QQ吗，2141916337
