### ISSUE TITLE
http://xxx:9006/6绕过登录访问资源怎么破?

### ISSUE THREAD

**Issue by InternetofThingsprogrammer** [qinguoyi/TinyWebServer#124]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/26659248/165548693-38376964-a018-42a0-ae27-bd8bc4a279f3.png">
在do_request()里加了个bool变量检查是否经过检验但是似乎没起作用,依旧可以直接绕过登录访问资源???

**Comment by InternetofThingsprogrammer** [comment]
我在http类里增加了一个bool的检测标志passck,在登录成功后将这个bool变量由初始化的false变为true,然后再访问/5,/6,/7的资源网页时加入passck为真的判断,这样做可以解决客户端第一次登录前直接访问/5,/6,/7资源html的bug,但是用户第一次登录后,再填新开一个http://xxx:9006/6的网页,又可以不经过登录直接访问的bug依然存在?请问大佬们,接下来我应该怎么做,才能够完全解决这个bug?                    ----编程新手,请大佬指教一下

**Comment by InternetofThingsprogrammer** [comment]
忘了说了,我的passck添加http类的私有成员里,然后再析构函数里添加passck = false,在这个http对象被释放的时候回复passck的初值

**Comment by InternetofThingsprogrammer** [comment]
> 

请问我在析构函数里的这条passck = false语句为何不生效呢?

**Comment by InternetofThingsprogrammer** [comment]
即便是在close_conn()这里passck = false也无法解决这个bug?
![image](https://user-images.githubusercontent.com/26659248/165666097-d8557085-329b-45ce-b6cc-ca8996b6e05c.png)

**Comment by InternetofThingsprogrammer** [comment]
救命!!!!即便是在close_conn()这里passck = false;恢复bool值也无法解决这个bug???我真是太菜了呀!!!!难受
<img width="417" alt="image" src="https://user-images.githubusercontent.com/26659248/165666603-25d91ebd-6306-4d00-b879-a0e55c54a22b.png">
或者这里也不奏效
<img width="328" alt="image" src="https://user-images.githubusercontent.com/26659248/165666784-9d70bc97-1740-42e0-8e2d-bb2f7abe5790.png">

**Comment by InternetofThingsprogrammer** [comment]
难受,我为啥要发现这个bug????!!!!!

**Comment by InternetofThingsprogrammer** [comment]
发现需要在webserver这里更改passck的值
<img width="714" alt="image" src="https://user-images.githubusercontent.com/26659248/165678841-028df4cc-53ac-4221-adcd-61ebf18630d9.png">
但是不知道怎么怎么改....如何在webserver里访问当前的http_conn连接对象?

**Comment by Eren-cc** [comment]
没有添加cookie验证，这不是bug。可以自己加上

**Comment by InternetofThingsprogrammer** [comment]
> 没有添加cookie验证，这不是bug。可以自己加上

不会......可以不加cookie做到吗?例如加个校验位啥的?就是不知道怎么在定时结束的时候如何找到对应sockfd的http对象

**Comment by InternetofThingsprogrammer** [comment]
> 没有添加cookie验证，这不是bug。可以自己加上

太菜了,哈哈哈哈哈

**Comment by qinguoyi** [comment]
当前没有用户信息校验，是可以通过url直接访问的。
