### ISSUE TITLE
为什么当epoll_wait的结果中可能是新建立的一个连接时，还需要循环。

### ISSUE THREAD

**Issue by 2900322208** [qinguoyi/TinyWebServer#126]
在main函数的大概200行左右，当设置边缘触发时，如果监听到一个新建立连接的读事件，此时不应该把这个connfd直接加到监听树上就完事吗。换句话说，他循环读，读的是什么呢。希望大佬们解惑

**Comment by 2900322208** [comment]
Xdm有没有一起做这个的留个联系方式讨论讨论

**Comment by puppet12306** [comment]
ET模式需要把队列中所有的连接都添加到树上

**Comment by tomatowithpotato** [comment]
你是说raw_version版本里，main.c的217行，从#ifdef listenfdET到#endif这段内容吗？
因为这时listenfd是边缘触发态，虽然会有多个请求到达连接缓冲区，但边缘触发模式下只会触发一次读事件，因此必须在收到连接读事件后用非阻塞循环处理所有连接，否则后续不触发，那剩余的就没法连接了。

**Comment by 2900322208** [comment]
谢谢两位大哥，好像懂了
