### ISSUE TITLE
webbench测试的硬件参数（服务器配置什么的）是多少捏？

### ISSUE THREAD

**Issue by tomatowithpotato** [qinguoyi/TinyWebServer#128]
我在双核的云服务器上跑server，用另一个双核的云服务器跑跟测试用例一样的webbench，但为啥我跑出来的qps低的可怜呢？能处理的request才15000左右
请问实际测试时的配置是多少捏？

**Comment by 2900322208** [comment]
大佬跑的是raw_vesrion还是新代码。旧代码跑的时候除了修改数据库那些还要改啥，为啥我用云服务器跑不出

**Comment by 2900322208** [comment]
> 大佬跑的是raw_vesrion还是新代码。旧代码跑的时候除了修改数据库那些还要改啥，为啥我用云服务器跑不出

raw_version里没有build。。。

**Comment by 2900322208** [comment]
build了也不行，还需要修改什么啊大佬。执行完./server没有反应，浏览器输入ip：端口也访问不了
