### ISSUE TITLE
各位大佬，在写日志的时候，为啥m_buf不用清零呢

### ISSUE THREAD

**Issue by 2900322208** [qinguoyi/TinyWebServer#132]
如题，在raw_version里，异步写日志是通过调用LOG_INFO,再去调LOG里的write写到阻塞队列里的。然后我发现每次掉都是先写到m_buf,然后在赋值给一个临时的字符串，我想问的是，m_buf每次都直接赋值给那个临时字符串，也不看见他又清空操作（可能在别处我没发现），那之前的日志不一起拷进去了吗。

**Comment by 2900322208** [comment]
我的代码理解哪里出了问题吗，大佬们指点一下

**Comment by InternetofThingsprogrammer** [comment]
> 如题，在raw_version里，异步写日志是通过调用LOG_INFO,再去调LOG里的write写到阻塞队列里的。然后我发现每次掉都是先写到m_buf,然后在赋值给一个临时的字符串，我想问的是，m_buf每次都直接赋值给那个临时字符串，也不看见他又清空操作（可能在别处我没发现），那之前的日志不一起拷进去了吗。

啥是异步?

**Comment by InternetofThingsprogrammer** [comment]
> 如题，在raw_version里，异步写日志是通过调用LOG_INFO,再去调LOG里的write写到阻塞队列里的。然后我发现每次掉都是先写到m_buf,然后在赋值给一个临时的字符串，我想问的是，m_buf每次都直接赋值给那个临时字符串，也不看见他又清空操作（可能在别处我没发现），那之前的日志不一起拷进去了吗。

每次写满了,再拷贝,有啥问题?之前的日志被覆盖了

**Comment by 2900322208** [comment]
> > 如题，在raw_version里，异步写日志是通过调用LOG_INFO,再去调LOG里的write写到阻塞队列里的。然后我发现每次掉都是先写到m_buf,然后在赋值给一个临时的字符串，我想问的是，m_buf每次都直接赋值给那个临时字符串，也不看见他又清空操作（可能在别处我没发现），那之前的日志不一起拷进去了吗。
> 
> 每次写满了,再拷贝,有啥问题?之前的日志被覆盖了

我靠 糊涂了，忘了覆盖这回事 谢谢大佬。。。

**Comment by 2900322208** [comment]
> 



> > 如题，在raw_version里，异步写日志是通过调用LOG_INFO,再去调LOG里的write写到阻塞队列里的。然后我发现每次掉都是先写到m_buf,然后在赋值给一个临时的字符串，我想问的是，m_buf每次都直接赋值给那个临时字符串，也不看见他又清空操作（可能在别处我没发现），那之前的日志不一起拷进去了吗。
> 
> 啥是异步?

他写日志有两种模式，异步写的时候增加了一个日志信息的阻塞队列，就把生产者消费者模型封装为阻塞队列，工作线程把要写的内容push进队列，然后新建一个线程一直循环的从队列里面取信息执行写日志，工作线程把内容放进队列就能干别的事了，不用等写完日志了
