### ISSUE TITLE
为什么数据库连接池中的m_Port定义为string？

### ISSUE THREAD

**Issue by loook98** [qinguoyi/TinyWebServer#133]
https://github.com/qinguoyi/TinyWebServer/blob/7e103e82375d316403dbc0ea25d2feca7a2146b6/CGImysql/sql_connection_pool.h#L42

并且还在下边这里把int赋值给string？
https://github.com/white0dew/WebServer/blob/e5b4bc99928869cf4d7523cde1dc2177753c1eb9/CGImysql/sql_connection_pool.cpp#L29

这个m_Port好像也没有在其他地方用到。
下边这里用的是参数中的int类型的Port。
https://github.com/white0dew/WebServer/blob/e5b4bc99928869cf4d7523cde1dc2177753c1eb9/CGImysql/sql_connection_pool.cpp#L45

**Comment by InternetofThingsprogrammer** [comment]
如果你的数据库不止一个呢?就是不止本地一个.........在其他设备有同样数据库,你最后还是转string,不如早做了

**Comment by loook98** [comment]
> 如果你的数据库不止一个呢?就是不止本地一个.........在其他设备有同样数据库,你最后还是转string,不如早做了

问题不是这，转string也不是直接把int赋值给string吧。估计是写错了，刚好这个成员变量没有用到就没出bug。

**Comment by InternetofThingsprogrammer** [comment]
> > 如果你的数据库不止一个呢?就是不止本地一个.........在其他设备有同样数据库,你最后还是转string,不如早做了
> 
> 转string也不是直接把int赋值给string吧。估计是写错了吧，刚好这个成员变量没有用到就没出bug。

确实应该是写错了
