### ISSUE TITLE
怎么在云服务器上跑，除了修改数据库那部分还要改什么

### ISSUE THREAD

**Issue by 2900322208** [qinguoyi/TinyWebServer#136]
问一下跑出来的大佬，怎么在云服务器上跑出来。为啥我改了他说的快速运行里的数据库那部分，还是不行。之前看代码看的是raw_version,然后看了以后直接跑的重构版本

**Comment by 2900322208** [comment]
![image](https://user-images.githubusercontent.com/73978795/169015253-c92a3f8a-60e7-4590-a085-a87f82c5ee22.png)

**Comment by 2900322208** [comment]
![image](https://user-images.githubusercontent.com/73978795/169015756-3124a268-8b0d-4cde-a84a-99e74f4e0da5.png)

**Comment by 2900322208** [comment]
![image](https://user-images.githubusercontent.com/73978795/169016256-08b4bb06-04a5-4144-bf5a-1e7a99fbb86e.png)

**Comment by 2900322208** [comment]
![image](https://user-images.githubusercontent.com/73978795/169016553-f46cb322-46a1-46bb-939d-4fcae9685faf.png)
大佬们救救我

**Comment by 2900322208** [comment]
![image](https://user-images.githubusercontent.com/73978795/169034696-b1ec9981-ab16-4c02-8763-6c95c3e21df7.png)
zai在本地可以访问，外面输入ip：端口不可以 是因为防火墙吗大佬们

**Comment by 2900322208** [comment]
为啥同样的代码，只是数据库那部分不一样就跑不了呢。是不是云服务器上数据库和虚拟机有什么差异，我是改的云服务器上的登录名和密码，还有数据库名啊。防火墙是关的，端口是全开的

**Comment by tomatowithpotato** [comment]
应该是要设置防火墙的

**Comment by 2900322208** [comment]
> 你可以用telnet命令来测试你的端口是不是可以被访问的

你好 他是这样的9006 没有拒绝 我试了一个其他的拒绝了 ，是不是说明9006端口可以被访问
![image](https://user-images.githubusercontent.com/73978795/169198593-81945970-124c-43bc-9679-af0d5575a418.png)
![image](https://user-images.githubusercontent.com/73978795/169198663-995f952d-f6c9-4d46-9e9a-c1dcd0843ced.png)

**Comment by 2900322208** [comment]
> 你可以用telnet命令来测试你的端口是不是可以被访问的

成功了 谢谢兄弟  换了谷歌浏览器好了
