### ISSUE TITLE
TinyWebServer的项目交流群

### ISSUE THREAD

**Issue by tomatowithpotato** [qinguoyi/TinyWebServer#138]
不知道有没有这个项目的讨论群？？？？

我自己建了个群，叫TinyWebServer
qq群号: 720139064
主要是为了方便大家交流这个项目，有啥不懂得大家一起讨论，有兴趣的可以加群一起讨论

**Comment by tomatowithpotato** [comment]
打个广告，我自己写了个小项目，[https://github.com/tomatowithpotato/HAHA-WebServer](url)，大家要有兴趣可帮忙点个star，助力俺的秋招，小弟在此感激不尽

目前还在完善，如果有兴趣的话可以发issue提问

项目主要参考了[https://github.com/josexy/socnet-cpp](url) 和muduo

**Comment by qinguoyi** [comment]
支持一下，是有讨论群的，但是我目前没维护那个群了==
