### ISSUE TITLE
MySQL Error可能的解决办法

### ISSUE THREAD

**Issue by loook98** [qinguoyi/TinyWebServer#140]
新建的MySQL登录用户没有给权限，加上权限后就OK了。
>在创建用户账号后，必须接着分配访问权限。新创建的用户账号没有访
问权限。它们能登录MySQL，但不能看到数据，不能执行任何数据库操作。

**Comment by zhouwy-lv** [comment]
你好，请问怎么给登录用户赋予权限？这里的用户指的是数据库里的那个用户吗？

**Comment by loook98** [comment]
> 你好，请问怎么给登录用户赋予权限？这里的用户指的是数据库里的那个用户吗？

不是表里的那个「登录网站」的用户。我指的是「登录MySQL程序」的用户。

**Comment by 2060207050** [comment]
mysql error的话，用 sudo ./server 就好了

**Comment by chengyangliu47** [comment]
补充一下,我是安装的时候设置的密码是root,后来改成mysql要求的强密码后解决了,强密码要包含大小写,特殊符号,只少8位和最重要的不能是查得到的字典单词(如'admin')
