### ISSUE TITLE
win11 ubuntu1804 Mysql 连接问题

### ISSUE THREAD

**Issue by zhouwy-lv** [qinguoyi/TinyWebServer#141]
设备：小新win11 vmware16.2.3  ubuntu1804
Mysql连接问题。打印的错误号为：
2022-06-02 16:50:03.067831 [erro]: MySQL Error[errno=0]: 

user中已经插入对应的user 以及 passwd。

相同的过程在台式机中没有问题，可以连接到MYSQL，并且正常运行。但是台式机要用来跑实验。请问有大佬遇到相同的问题吗？是win11的问题还是其他的问题？

**Comment by DreamingRs7** [comment]
兄弟，你把登录数据库需要加sudo的问题解决就行了。

**Comment by zhouwy-lv** [comment]
> 
你好，你的意思是要设置好以后登录数据库不需要+sudo是吗

**Comment by zhouwy-lv** [comment]
你好，你的意思是要设置好以后登录数据库不需要+sudo是吗

DreamingRs7 ***@***.***> 于2022年6月18日周六 22:39写道：

**Comment by DreamingRs7** [comment]
是的，我用的也是ubuntu18.04，遇到过这个问题。

**Comment by zhouwy-lv** [comment]
谢谢

DreamingRs7 ***@***.***> 于2022年6月21日周二 14:35写道：
