### ISSUE TITLE
日志系统

### ISSUE THREAD

**Issue by PAWCOOK-ADMIN** [qinguoyi/TinyWebServer#142]
请问日志系统的阻塞队列的同步，为什么使用条件变量和互斥量实现呢？信号量和互斥量实现会不会更好

**Comment by tomatowithpotato** [comment]
额，其实我觉得都大差不差，信号量某种意义上就是条件变量与互斥量的组合实现

**Comment by qinguoyi** [comment]
不同的实现方式哈，没有必须用哪一种
