### ISSUE TITLE
为啥./server后，进程状态显示Sl+

### ISSUE THREAD

**Issue by Ron-Cyber008** [qinguoyi/TinyWebServer#143]
按照快速部署的方式，根本行不通啊，而且也没说明数据库是本地的还是其他服务器上的？不会只有我一个人是跑不通吧

**Comment by lueluelue1998** [comment]
我按照快速部署的方式也没有跑通，不知道问题出在哪

**Comment by qinguoyi** [comment]
> 按照快速部署的方式，根本行不通啊，而且也没说明数据库是本地的还是其他服务器上的？不会只有我一个人是跑不通吧

当前的快速部署，是默认用户已经搭建好系统和MySQL服务了，mysql的ip是本地还是其他机器没有关系，只要能连通访问就行。

具体的问题可以贴图看看呢，issue里的问题比较全了

**Comment by lueluelue1998** [comment]
这是来自QQ邮箱的假期自动回复邮件。

您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
