### ISSUE TITLE
程序可以运行但是输入网页显示404

### ISSUE THREAD

**Issue by guanshuzhi** [qinguoyi/TinyWebServer#147]

**Comment by qinguoyi** [comment]
补充下日志和截图看看呢

**Comment by Xiloy** [comment]
你好我也是这个问题，不过我的代码是c++11简洁版本的webserver，而且运行makefile网页都可以正常显示出来，但是我用code runner能成功运行，但是网页报404的错误，下面是我的日志 
![Screenshot from 2023-03-01 11-27-40](https://user-images.githubusercontent.com/67252481/222037607-6f8ebe7f-b59a-4b4a-ab16-95dea7ed5f28.png)
