### ISSUE TITLE
新手小白，请问./server之后应该做什么呀？./server后shell直接卡住不动了啊啊啊

### ISSUE THREAD

**Issue by whj169877** [qinguoyi/TinyWebServer#149]
新手小白，请问./server之后应该做什么呀？./server后shell直接卡住不动了啊啊啊

**Comment by gtoo8888** [comment]
那个不是卡住不动，./server以后没有继续显示是正常的。你正常应该是在远程的linux服务器上面运行了你的./server(比如你的虚拟机，或者你远端连接的服务器)，你需要获取到这服务器的IP比如我的是192.168.0.3，这时候回到你自己电脑用的浏览器上，比如我用的是edge，在地址栏中输入http://192.168.0.3:9006，如果你没有改过程序的话，后面的9006是这个服务器默认的端口号，这时候你应该可以看到页面了，就可以开始玩了

**Comment by whj169877** [comment]
谢谢大佬，已经开始玩儿了哈哈

**Comment by lqz2** [comment]
> 

请问./server 打开了，但是浏览器输入ip和端口号后显示You do not have permission to get file form this server.
这个怎么解决呢

**Comment by whj169877** [comment]
> > 
> 
> 请问./server 打开了，但是浏览器输入ip和端口号后显示You do not have permission to get file form this server. 这个怎么解决呢

emm,没有遇到过这个问题，你可以看一下Project根目录有没有报错文件，找到更详细的报错信息~可能是mysql授权问题，也可能是没用root用户？

**Comment by qinguoyi** [comment]
> > 
> 
> 请问./server 打开了，但是浏览器输入ip和端口号后显示You do not have permission to get file form this server. 这个怎么解决呢

chmod -R 777 修改下整个文件的权限即可
