### ISSUE TITLE
mysql连接中总是出现段错误SELECT error:Table 'yudb.user' doesn't exist

### ISSUE THREAD

**Issue by wyq15** [qinguoyi/TinyWebServer#153]
之前出现MySQL Error[errno=1045]: Access denied for user 'XXX'@'localhost' (using password: YES)这样的错误，添加了skip-grant-tables之后变成现在的错误了。
最开始还有这样的错误 MySQL Error[errno=2002]: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)  靠重新卸载安装解决的。
有没有人遇到过和我一样的错误呢？希望得到大家的指点，谢谢！

**Comment by lqz2** [comment]
数据库新创建一个用户，设置好密码，授予这个用户所有权限，然后把user表里的你创建的用户的host改成%，表示能从所有ip连接到数据库，设置好之后试一下远程连接mysql，如果能用你创建的这个用户远程连接就行
