### ISSUE TITLE
make时出现mysql.h找不到的报错，按楼主提示的方法依旧不成功

### ISSUE THREAD

**Issue by li200005** [qinguoyi/TinyWebServer#160]
make报错说mysql找不到，sudo apt-get install libmysqlclient-dev报404 not found的错误，请问这是什么原因呢？
![image](https://user-images.githubusercontent.com/58905357/183290278-4c1ba309-c601-4752-abcf-0c2923547e17.png)

**Comment by li200005** [comment]
我用的是wsl Ubuntu20.04，尝试过sudo apt-get upgrade，以及试了几种百度的办法还是不行，只好向各位请教下

**Comment by MoreActiL** [comment]
我用 `sudo apt install libmysqlclient-dev` 可以安装，是不是 `apt` 和 `apt-get` 的问题？
<img width="704" alt="image" src="https://user-images.githubusercontent.com/101028805/187204581-cf471a7f-3e5b-494c-b8fb-b0510f7801bc.png">
