### ISSUE TITLE
为什么最大文件描述符限制是1024，但用webbench压测能达到10000并发量？

### ISSUE THREAD

**Issue by Aviram-hub** [qinguoyi/TinyWebServer#164]
这10000个客户端不是每一个都占用一个文件描述符吗？

**Comment by tomatowithpotato** [comment]
因为最大文件描述符默认1024，但实际上这个值是可以通过命令去修改的

**Comment by Aviram-hub** [comment]
但是我没有改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月13日(周六) 晚上7:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qinguoyi/TinyWebServer] 为什么最大文件描述符限制是1024，但用webbench压测能达到10000并发量？ (Issue #164)




 
因为最大文件描述符默认1024，但实际上这个值是可以通过命令去修改的

**Comment by tomatowithpotato** [comment]
可能你的机器默认值已经被改了
用这个命令ulimit -n去看

**Comment by Aviram-hub** [comment]
看过了，没改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月13日(周六) 晚上8:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qinguoyi/TinyWebServer] 为什么最大文件描述符限制是1024，但用webbench压测能达到10000并发量？ (Issue #164)




 
可能你的机器默认值已经被改了
 用这个命令ulimit -n去看
