### ISSUE TITLE
./server之后啥也没有，浏览器端连接也连不上，纯小白很懵逼

### ISSUE THREAD

**Issue by JiaFangzheng** [qinguoyi/TinyWebServer#171]
前面都是照着readme一步一步做的，做到make server的时候有一些warning但是也make出来了，但是执行的时候就不行了。。。日志都指的是文件夹里的那个日志文件吗？我点开发现啥也没有，也不知道咋看。。。日志完全是空的。现在不知道咋办了，大佬们救一下

**Comment by Carey-ma** [comment]
应该是VMware网络设置的问题，你直接在VMware里面的浏览器输入IP:端口就行

**Comment by JiaFangzheng** [comment]
> 应该是VMware网络设置的问题，你直接在VMware里面的浏览器输入IP:端口就行
sudo ./server 192.168.42.128 9006
感觉没啥问题啊，虚拟机里的火狐我连也连不上，很懵逼

**Comment by Carey-ma** [comment]
./server
然后在浏览器输入：
192.168.42.128:9006

**Comment by JiaFangzheng** [comment]
[Assertion `ret >= 0' failed.](server: main.c:144: int main(int, char**): Assertion `ret >= 0' failed.)
我靠，又有新问题了，现在执行都不行了，报这个错

**Comment by JiaFangzheng** [comment]
太离谱了，重启一下虚拟机之后啥都好了，全跑通了。。。。重启yyds！

**Comment by WMLMLML** [comment]
默认端口9006，你重启./server，这个端口还是被占用，可以换个端口
