### ISSUE TITLE
新用户登录问题

### ISSUE THREAD

**Issue by WMLMLML** [qinguoyi/TinyWebServer#175]
请问一下为什么我直接在数据库记录账号密码信息的表中添加新用户这样做不行呢？

**Comment by qinguoyi** [comment]
> 请问一下为什么我直接在数据库记录账号密码信息的表中添加新用户这样做不行呢？

应该是可以的哦，注册本质就是插入数据。有具体的现象或者报错吗

**Comment by WMLMLML** [comment]
我的问题，当时没有测试完整。可以在数据库表中直接添加新用户，之后重启一下服务器就行。

**Comment by WMLMLML** [comment]
> > 请问一下为什么我直接在数据库记录账号密码信息的表中添加新用户这样做不行呢？
> 
> 应该是可以的哦，注册本质就是插入数据。有具体的现象或者报错吗

我的问题，当时没有测试完整。可以在数据库表中直接添加新用户，之后重启一下服务器就行。
