### ISSUE TITLE
webbench编译时错误

### ISSUE THREAD

**Issue by Dywane677** [qinguoyi/TinyWebServer#176]
![image](https://user-images.githubusercontent.com/109772692/192462689-030b8cc8-354d-4a7d-b014-d6dd4537d3b4.png)

**Comment by qinguoyi** [comment]
> ![image](https://user-images.githubusercontent.com/109772692/192462689-030b8cc8-354d-4a7d-b014-d6dd4537d3b4.png)

可以看下这个解决方案：https://blog.csdn.net/dxgzg/article/details/120913307
