### ISSUE TITLE
代码调试中的疑问

### ISSUE THREAD

**Issue by musongfangchen** [qinguoyi/TinyWebServer#2]
你好：我最近一直在学习研读调试你的Tinywebserver ，想请教一下，在http_conn.cpp文件中，有关修改数据库初始化信息，中有connection_pool *connPool=connection_pool::GetInstance("localhost", "root","root","yourdb",3306,5);这其中 “localhost” 应该输入啥？ 我的开发环境是在VMware workstation 12 Pro 上安装 ubuntu16.04LTS ，服务器程序实在VMware workstation12 上的ubuntu16.04上编译的，请问此处的"localhost"应该填虚拟机ubuntu16.04的ip地址还是我笔记本的ip地址？如能帮忙解答，将不胜感激！我微信号15829468779,如能与你成为微信好友，深感荣幸！

**Comment by Liu-YT** [comment]
这个应该是填运行数据库的主机的host吧，这个是用于连接mysql数据库的配置，如果在虚拟机内启动直接写`localhost`就可以了的吧

**Comment by qinguoyi** [comment]
> 你好：我最近一直在学习研读调试你的Tinywebserver ，想请教一下，在http_conn.cpp文件中，有关修改数据库初始化信息，中有connection_pool *connPool=connection_pool::GetInstance("localhost", "root","root","yourdb",3306,5);这其中 “localhost” 应该输入啥？ 我的开发环境是在VMware workstation 12 Pro 上安装 ubuntu16.04LTS ，服务器程序实在VMware workstation12 上的ubuntu16.04上编译的，请问此处的"localhost"应该填虚拟机ubuntu16.04的ip地址还是我笔记本的ip地址？如能帮忙解答，将不胜感激！我微信号15829468779,如能与你成为微信好友，深感荣幸！

直接写localhost即可
