### ISSUE TITLE
编译运行问题

### ISSUE THREAD

**Issue by wenjian11** [qinguoyi/TinyWebServer#205]
![image](https://user-images.githubusercontent.com/48944670/222326220-8effb4e0-137d-4d6c-9127-731590a26d4f.png)
按照教程，报错如下，不知道是哪里的问题。谢谢解答。

**Comment by Chan7348** [comment]
我也是这样，请问有解决方案了吗

**Comment by wenjian11** [comment]
我换了他的另外一个分支就可以了，好像是这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月1日(星期四) 晚上7:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 编译运行问题 (Issue #205)





 
我也是这样，请问有解决方案了吗

**Comment by Chan7348** [comment]
没事，这些都不是报错只是警告
