### ISSUE TITLE
关于webserver代码问题

### ISSUE THREAD

**Issue by liuwuyao** [qinguoyi/TinyWebServer#21]
前辈你好，我有几个疑问
1.webserver类中定义了一个sort_timer_lst变量timer_lst，代码中操作的也都是变量timer_lst。但是最后在eventloop函数使用了utils.timer_hander（）函数。utils对象的初始化使用的是最开始定义的timer_lst，后面utils对象的m_timer_lst没有进行更新.
我觉得是不是把utils对象的初始化放在webserver类的构造函数，后面统一对utils.m_timer_lst操作。要么就是改eventloop中的代码。
2.
//处理新到的客户连接
            if (sockfd == m_listenfd)
            {
                bool flag = dealclinetdata();
                if (false == flag)//？？？？？
                   continue;
            }
这里的if判断条件是什么作用呢？我猜测是不是你想在flag==false的情况下输出日志，代码未完成吗？感谢解答

**Comment by qinguoyi** [comment]
你好，

第一个，确实有问题，可以每次调整timer_lst后都调用utils.init更新m_timer_lst。另外，把utils放在webserver类初始化，逻辑上没问题，但过于耦合，虽然现在也过于强耦合了，（逃...

第二个，当前循环中是分支语句，如果在分支语句后还有其他语句，这个代码可以跳过之后的语句执行。但，if (false == flag)在当前代码中没有任何作用，可以删掉。

感谢。
