### ISSUE TITLE
要求上说，linux版本一定是Ubuntu16，Ubuntu18或centos7可以吗？

### ISSUE THREAD

**Issue by zhang123-sys** [qinguoyi/TinyWebServer#216]

**Comment by qinguoyi** [comment]
这个项目没有过多依赖操作系统，linux都可以

**Comment by zhang123-sys** [comment]
谢谢，我运行成功您的TinyWebServer后，由运行您的WebServer，只是不知道浏览器的访问端口号




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 晚上7:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 要求上说，linux版本一定是Ubuntu16，Ubuntu18或centos7可以吗？ (Issue #216)





 
这个项目没有过多依赖操作系统，linux都可以
