### ISSUE TITLE
blocking_queue的push操作为什么不能用m_cond.signal

### ISSUE THREAD

**Issue by ahjdzx** [qinguoyi/TinyWebServer#22]
https://github.com/qinguoyi/TinyWebServer/blob/master/log/block_queue.h#L124
@qinguoyi

**Comment by qinguoyi** [comment]
> https://github.com/qinguoyi/TinyWebServer/blob/master/log/block_queue.h#L124
> @qinguoyi

你好，是可以用signal的。

broadcast和signal使用规则如下，引用opengroup的陈述，

1.下面情况适合用pthread_cond_broadcast

  一个生产者多消费者，生产者能一次产生多个产品的情况。
  多生产者多消费者
  读写锁实现（写入之后，通知所有读者）
  
2.下面情况适合pthread_cond_signal的情况

单一生产者，生产者一次生产一个产品的情况，最好一个消费者

综上所述，两者的区别在于消费者的数量，具体的表现在线程数量。项目中只有异步日志会使用push和pop，且只有一个线程，所以可以使用signal。
