### ISSUE TITLE
执行./server显示Segmentation fault (core dumped)，执行sudo ./server日志中显示MySQL ERROR

### ISSUE THREAD

**Issue by mingshanqiu** [qinguoyi/TinyWebServer#223]
已经按照的issue修改了 webserver.cpp的localhost还有'root'@'localhost'，但还是出现了以上问题

![问题](https://user-images.githubusercontent.com/91071101/234057799-42eab3a6-254e-489e-91f8-bcc0bd691c0e.png)

**Comment by TalentFang** [comment]
看一下是不是内存不足？可以看一下core文件

**Comment by mingshanqiu** [comment]
已经解决了，main.cpp文件中数据库初始化信息passwd 应该填写自己的密码而不是root

**Comment by 11days** [comment]
自己填写的密码是啥啊，我安装mysql时填的是123456，然后user用的是debian-sys-maint，但是不行
