### ISSUE TITLE
网页打不开

### ISSUE THREAD

**Issue by nanhai78** [qinguoyi/TinyWebServer#232]
我是在局域网下有一台带桌面ubuntu的服务器，在服务器上起web项目，然后使用浏览器自己访问自己是可以的。
但是我在局域网下的另一台win10电脑下，使用局域网IP(192.168.0.108) + 端口号，却访问不了。查了很多没找到解决办法，有没有大佬解答下，SSH是可以访问ubuntu服务器的，所以网络应该没问题

**Comment by qinguoyi** [comment]
1. 互ping一下ip，看看是否ping通
2. telnet ip port，看看是否能通
