### ISSUE TITLE
make后无法运行 报错 './server' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by fhawk12** [qinguoyi/TinyWebServer#238]
![image](https://github.com/qinguoyi/TinyWebServer/assets/44942692/bc65343d-2cf6-4f34-b7ef-48d4ac55a732)
![image](https://github.com/qinguoyi/TinyWebServer/assets/44942692/1119e73c-dbe6-4595-b28d-eff3690f2b4a)
![image](https://github.com/qinguoyi/TinyWebServer/assets/44942692/cd1cda66-54b6-42bd-a065-e891e7898d3a)

**Comment by fhawk12** [comment]
how to fix it, please help me, thanks

**Comment by Mr-Jacks520** [comment]
It seems that there are some errors in memory access, based on the console error messages. The errors occur when attempting to access an invalid memory location, such as a null pointer or something similar.

You can try the following methods to **identify** the location of the errors:

1. Use `gdb` to debug your program and obtain the error location.
2. Utilize the command `coredumpctl gdb processID` to investigate where the errors are occurring. However, please note that you must first know the process ID of your program before using this command.

**Comment by fhawk12** [comment]
It's useful, I find where I was wrong,  my database field name is "password", but it should be "passwd". Thank you for your advice!
