### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by Blakeyi** [qinguoyi/TinyWebServer#25]
在centos7里面用 火狐 打开 IP:9006可以正常显示界面，但是无法播放视频（显示没有找到支持的视频格式） 可能是浏览器问题
另外在win10里以 IP:9006 无法打开界面

**Comment by qinguoyi** [comment]
最新的代码如果无法播放视频，是浏览器问题。

win10中无法打开界面，首先通过ping查看网络是否可以正常访问。
