### ISSUE TITLE
./server 正常运行    服务器访问报错PR_END_OF_FILE_ERROR   然后./server  就显示段错误

### ISSUE THREAD

**Issue by ztms123** [qinguoyi/TinyWebServer#253]
![image](https://github.com/qinguoyi/TinyWebServer/assets/81799631/34127093-8ad4-41ff-84ff-aab07c7fa8f3)

**Comment by zhaoting-git** [comment]
https://zhuanlan.zhihu.com/p/641038731这个文看看

**Comment by zhaoting-git** [comment]
https://zhuanlan.zhihu.com/p/641038731
这个文你看看，我也是这个问题。

**Comment by zhaoting-git** [comment]
https://zhuanlan.zhihu.com/p/641038731
https://zhuanlan.zhihu.com/p/657997475
这两个文你看看，我也是这个问题，应该是程序有bug.

**Comment by ztms123** [comment]
> https://zhuanlan.zhihu.com/p/641038731 https://zhuanlan.zhihu.com/p/657997475 这两个文你看看，我也是这个问题，应该是程序有bug.

感谢  我换了master分支可以了
