### ISSUE TITLE
http_conn类问题

### ISSUE THREAD

**Issue by liuwuyao** [qinguoyi/TinyWebServer#26]
前辈你好：
http_conn.c 文件的users（就是用户的map），是不是应该设置成staic类型的。如果是非static类型的，每次来一个链接，就应该从数据库拷贝一次用户名和密码表，但http_conn::init()函数没有进行这一操作，webserver.c也只是拷贝了一次。另外，微信群怎么加入啊，希望和大家一起讨论。

**Comment by pansn1995** [comment]
> 前辈你好：
> http_conn.c 文件的users（就是用户的map），是不是应该设置成staic类型的。如果是非static类型的，每次来一个链接，就应该从数据库拷贝一次用户名和密码表，但http_conn::init()函数没有进行这一操作，webserver.c也只是拷贝了一次。另外，微信群怎么加入啊，希望和大家一起讨论。

感觉http_conn类中的map没有用到，注释掉就可以了，他其实用的是一个全局map的user，好好看看就晓得了

**Comment by liuwuyao** [comment]
> > 前辈你好：
> > http_conn.c 文件的users（就是用户的map），是不是应该设置成staic类型的。如果是非static类型的，每次来一个链接，就应该从数据库拷贝一次用户名和密码表，但http_conn::init()函数没有进行这一操作，webserver.c也只是拷贝了一次。另外，微信群怎么加入啊，希望和大家一起讨论。
> 
> 感觉http_conn类中的map没有用到，注释掉就可以了，他其实用的是一个全局map的user，好好看看就晓得了

我明白了，谢谢

**Comment by qinguoyi** [comment]
> 前辈你好：
> http_conn.c 文件的users（就是用户的map），是不是应该设置成staic类型的。如果是非static类型的，每次来一个链接，就应该从数据库拷贝一次用户名和密码表，但http_conn::init()函数没有进行这一操作，webserver.c也只是拷贝了一次。另外，微信群怎么加入啊，希望和大家一起讨论。

群聊超过200人，只能邀请进群了，请加我微信twomonkeyscluber，谢谢。
