### ISSUE TITLE
不知道啥原因，原始版本LT+ET模式效率低

### ISSUE THREAD

**Issue by 114153** [qinguoyi/TinyWebServer#28]
main.c修改如下
`//#define listenfdET`
`#define listenfdLT `

http_conn.cpp修改如下
`#define connfdET`
`//#define connfdLT`

LT+ET
运行结果如下
![微信图片_20200620183524](https://user-images.githubusercontent.com/43237814/85199796-d7dcfc80-b324-11ea-8e7f-feb26bcf778a.png)

LT+LT
模式运行结果如下
![1592649515(1)](https://user-images.githubusercontent.com/43237814/85199896-900aa500-b325-11ea-9f59-c6aa91b66017.png)

**Comment by 114153** [comment]
好像找到问题了，main.c中在将listenfd添加到epoll树上的时候，调用addfd，而addfd中只关心connfdET还是connfdLT，所以误把listenfd设成了ET模式，大概就是addfd函数出错了
社长在设置connfdET时，应该没考虑到listenfd的模式？
如果可以的话，社长能确认下。。。。

**Comment by qinguoyi** [comment]
> 好像找到问题了，main.c中在将listenfd添加到epoll树上的时候，调用addfd，而addfd中只关心connfdET还是connfdLT，所以误把listenfd设成了ET模式，大概就是addfd函数出错了
> 社长在设置connfdET时，应该没考虑到listenfd的模式？
> 如果可以的话，社长能确认下。。。。

你好，旧版本确实如此，新版本不存在这个bug。

大致思路是修改addfd，如新版本所示，添加一个listenfd和connfd的模式参数。

我尽快修复，感谢反馈。
