### ISSUE TITLE
log.cpp中的log::init函数中的异步问题

### ISSUE THREAD

**Issue by heroazhe** [qinguoyi/TinyWebServer#29]
这里是通过条件变量来实现数组大小的同步问题吧，那个异步体现在了哪里？   代码中说的是//flush_log_thread为回调函数,这里表示创建线程异步写日志，这里只是开了一个线程来运行flush_log_thread函数吧，我认为本质应该还是线程同步问题吧，这里还请解答一下

**Comment by qinguoyi** [comment]
是的，本质上是将日志暂时存储在内存数组中，来缓解峰值响应慢的问题。
同步是日志串行写入磁盘，如果遇到磁盘io瓶颈(写入比较慢)，则程序响应也会变慢。
异步是日志先写入队列(内存)，另外创建线程异步写入磁盘，当遇到磁盘io瓶颈，队列中可以缓存部分数据，避免响应变慢。

ps: flush_log_thread内部会调用async_write_log，从队列中获取日志写入磁盘。
