### ISSUE TITLE
http_conn类中improv和timer_flag两个变量的意义

### ISSUE THREAD

**Issue by klq-Y** [qinguoyi/TinyWebServer#30]
请问，http_conn类中improv和timer_flag两个变量分别代表什么含义，起到什么作用？

**Comment by heroazhe** [comment]
timer_flag应该是timer到期的标志，improv是线程处理了相应的sockfd后，将其置为1，然后在dealwiththread中判断线程处理过的fd,并再将其置为0,以便后续的连接继续使用该fd。

**Comment by heixxxx** [comment]
timer_flag我仔细看了一下,它只在read_once和write返回false时被设置为1,即网络io已完成或失败时触发这个flag位.
而触发timer_flag后的处理是主线程调用deal_timer(),即断开用户的连接并删除对应timer定时器.
所以这个timer_flag应该是个用户连接是否异常的标志位吧?感觉和定时器没啥关系.

**Comment by heixxxx** [comment]
improv标志在read_once和write成功后,都会被设置为1,在相应的request处理完成后,均会被设置位
为0,所以这个标志是用来判断上一个请求是否已处理完毕

**Comment by MYMarcoreus** [comment]
http连接有两个标志位：`imporv`和`timer_flag`，初始时其值为0，它们只在`Reactor`模式下发挥作用。因为在`Reactor`模式中，主线程只负责监听读/写事件（得知有读写数据了），线程池中的线程负责IO操作（真正地读/写数据），但是如果线程池中的子线程进行客户的IO操作时，出现错误了，这时就需要设置`imporv`和`timer_flag`这两个标志位来告知主线程：“子线程我呀，对这个客户的IO操作，它，出！错！了！，你关闭掉这个客户的连接吧！”，于是主线程就知道要关闭这个IO出错的客户的连接。

下面是源代码中这两个标志具体的设置流程（子线程和主线程对IO出错的客户的交互）：
- 在`threadpool<T>::run()`中的`request->read_once()`或`request->write()`完成后`imporv`会被置1，标志着http连接的读写任务已完成（请求已处理完毕）；如果http连接的读写任务失败（请求处理出错）`timer_flag`会被置1。

- 在` WebServer::dealwith_read()`和`WebServer::dealwith_write()`中，会循环等待连接`improv`被置1，也就是一直等待该http连接的请求处理完毕，如果请求处理失败则关闭该http连接。

这些是我个人对这两个标志的理解，若有不对之处，请指正！
