### ISSUE TITLE
请问一下你的cgi文件是怎么定义的？

### ISSUE THREAD

**Issue by HLH13297997663** [qinguoyi/TinyWebServer#33]
cgi文件是怎么定义的，通过什么函数或方法接收前端传过来的用户数据？

**Comment by thygyc** [comment]
同问，cgi 文件没找到啊，楼主现在知道怎么回事了吗

**Comment by EdYYL** [comment]
同问

**Comment by liushuai839** [comment]
楼主找到cgi 文件了吗

**Comment by bluesea0** [comment]
同问，博主是把处理逻辑放到了`http_conn.cpp`的`do_request()`中，没有之前提到的`sign.cpp`文件了

**Comment by Ivringdai** [comment]
CGI校验这一部分已经删除了

**Comment by qinguoyi** [comment]
最新的版本已经删除了cgi校验，这个架构已经被主流废弃了，原始版本里还可以看到。
