### ISSUE TITLE
为什么write完成后，清空读缓冲区？

### ISSUE THREAD

**Issue by Jing0607101510** [qinguoyi/TinyWebServer#34]
http_conn.h和http_conn.cpp中，如果read_once函数读取的数据跨越了前一个请求和后一个请求的HTTP报文，那么在调用write函数在某些条件下，调用了init()函数，清空了读缓冲区，那么后一个请求的一部分数据不就丢失了？

**Comment by bluesea0** [comment]
如果主线程中调用`read_once`，LT模式下只执行一次`recv`，读取到不完整的http请求，然后用`http_conn::process()`，`process_read`就会返回NO_REQUEST，表示请求不完整，继续监听EPOLLIN事件。
不会执行到`write`函数

**Comment by ZuoFuhong** [comment]
> 如果read_once函数读取的数据跨越了前一个请求和后一个请求的HTTP报文...

在 HTTP 1.1 中，单个 TCP 连接同时处理一个请求，虽然存在 Pipelining 技术支持多个请求同时发送，但由于实践中存在很多问题无法解决，所以浏览器默认是关闭，所以可以认为是不支持同时多个请求。也就不会存在读取的数据跨越了前后两个请求的 HTTP 报文。
https://stackoverflow.com/questions/30477476/why-is-pipelining-disabled-in-modern-browsers/40688337#40688337
