### ISSUE TITLE
想问一下网络编程0基础的人要学些什么才能跟着这个项目做一遍？

### ISSUE THREAD

**Issue by notfresh** [qinguoyi/TinyWebServer#41]
目前学完了C++ 基本功，和基本的多线程编程知识，想了解一下如果想跟得上这个项目，需要储备什么知识呢？

光看游双那本书够吗？

请大家指点一下~

**Comment by Yoka416** [comment]
把这本书吃透肯定能搞下项目，问题是书里很多知识点讲的很浅，需要结合B站一些视频还有自己多动手做才能搞下来，没个半年搞不定的。



---原始邮件---
发件人: "张三思"<notifications@github.com&gt;
发送时间: 2021年1月11日(周一) 中午11:11
收件人: "qinguoyi/TinyWebServer"<TinyWebServer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [qinguoyi/TinyWebServer] 想问一下网络编程0基础的人要学些什么才能跟着这个项目做一遍？ (#41)




 
目前学完了C++ 基本功，和基本的多线程编程知识，想了解一下如果想跟得上这个项目，需要储备什么知识呢？
 
光看游双那本书够吗？
 
请大家指点一下~

**Comment by notfresh** [comment]
> 把这本书吃透肯定能搞下项目，问题是书里很多知识点讲的很浅，需要结合B站一些视频还有自己多动手做才能搞下来，没个半年搞不定的。
> […](#)
> ---原始邮件--- 发件人: "张三思"<notifications@github.com&gt; 发送时间: 2021年1月11日(周一) 中午11:11 收件人: "qinguoyi/TinyWebServer"<TinyWebServer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [qinguoyi/TinyWebServer] 想问一下网络编程0基础的人要学些什么才能跟着这个项目做一遍？ (#41) 目前学完了C++ 基本功，和基本的多线程编程知识，想了解一下如果想跟得上这个项目，需要储备什么知识呢？ 光看游双那本书够吗？ 请大家指点一下~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

半年啊。。。。。我无法接受
