### ISSUE TITLE
编译成功了，但是 ./server 5009 的时候，打开网页 http://localhost:5009/ 显示 unable to connect ?

### ISSUE THREAD

**Issue by AaronCMM** [qinguoyi/TinyWebServer#42]

**Comment by chenxiaohang** [comment]
解决了吗？我也遇到这个问题。请教一下

**Comment by 3614zys** [comment]
我直接将源代码编译运行也是这样，编译可以通过，无法连接是什么情况呢，解决了吗

**Comment by hadisi1993** [comment]
我也遇到这个问题，请问解决了吗

**Comment by 3614zys** [comment]
我用的是阿里云服务器，端口没开，不知道你是否是同样的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月28日(星期天) 上午9:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 编译成功了，但是 ./server 5009 的时候，打开网页 http://localhost:5009/ 显示 unable to connect ? (#42)





 
我也遇到这个问题，请问解决了吗

**Comment by hadisi1993** [comment]
我运行程序的时候，服务是启动的，但端口没开启

**Comment by Vegeta001** [comment]
请问下有解决吗？同样问题

**Comment by YouzhiHe** [comment]
请问有人解决了吗？急！！！

**Comment by Dzy-HW-XD** [comment]
如果是云服务器的话建议看一下防火墙有没有开启端口

**Comment by hadisi1993** [comment]
谢谢，已解决

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinguoyi/TinyWebServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月23日(星期天) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinguoyi/TinyWebServer] 编译成功了，但是 ./server 5009 的时候，打开网页 http://localhost:5009/ 显示 unable to connect ? (#42)





 
如果是云服务器的话建议看一下防火墙有没有开启端口
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by honor-greenhand** [comment]
你好，这个问题解决了吗

**Comment by honor-greenhand** [comment]
> 谢谢，已解决
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "qinguoyi/TinyWebServer"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年1月23日(星期天) 晚上6:41
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [qinguoyi/TinyWebServer] 编译成功了，但是 ./server 5009 的时候，打开网页 http://localhost:5009/ 显示 unable to connect ? (#42)
> 
> 
> 
> 
> 
>  
> 如果是云服务器的话建议看一下防火墙有没有开启端口
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you commented.Message ID: ***@***.***&gt;

你好，我的云服务器安全组端口是打开的，也出现这个问题，请问你就是安全组的问题吗

**Comment by qinguoyi** [comment]
> > 谢谢，已解决
> > ------------------ 原始邮件 ------------------
> > 发件人:                                                                                                                        "qinguoyi/TinyWebServer"                                                                                    _**@**_._**>;
> > 发送时间: 2022年1月23日(星期天) 晚上6:41
> > _**@**_.**_>;
> > _**@**_._**_**@**_.**_>;
> > 主题: Re: [qinguoyi/TinyWebServer] 编译成功了，但是 ./server 5009 的时候，打开网页 http://localhost:5009/ 显示 unable to connect ? (#42)
> > 如果是云服务器的话建议看一下防火墙有没有开启端口
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android.
> > You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 你好，我的云服务器安全组端口是打开的，也出现这个问题，请问你就是安全组的问题吗

一般先打开安全组，服务器监听下端口nc -lk port , 客户端telnet试下。如果能通，再看代码问题
