### ISSUE TITLE
如何下手好难

### ISSUE THREAD

**Issue by luo-xu** [qinguoyi/TinyWebServer#43]

**Comment by heixxxx** [comment]
去看那个原始版本,从main函数怎么初始化和启动服务的部分开始看,搞清楚总体流程了之后,再去细看各个模块怎么写的,我也是这周刚开始看,刚刚捋顺总体流程

**Comment by WYGNG** [comment]
搞过一段时间的通信节点开发,感觉还好,socket基础,pthread基础,c++基础,linux io基础,积累多了就理解流畅了,我感觉70%已知30%未知的学习是最舒服的,可以学的非常透彻而且不怎么吃力.

**Comment by SpringStudent** [comment]
老哥这个能不能windows环境下debug运行呢，刚刚接触C++，发现和JAVA不一样。

**Comment by WYGNG** [comment]
我忘记了

**Comment by HandsomeJims** [comment]
> 老哥这个能不能windows环境下debug运行呢，刚刚接触C++，发现和JAVA不一样。

本地用CLion链接Linux服务器开发即可
