### ISSUE TITLE
求助：日志打印错误信息为timer tick。server已开启，但无法在浏览器上连接到server

### ISSUE THREAD

**Issue by Vegeta001** [qinguoyi/TinyWebServer#52]

**Comment by ma-nual** [comment]
你好，我也遇到了这个问题，请问你找到解决办法了吗？

**Comment by HeJian0515** [comment]
我也遇到了，请问有解决方法吗？

**Comment by HeJian0515** [comment]
timer tick不是错误，我真正的错误是不能访问root文件夹的资源。改变root文件夹的权限就好了。

**Comment by ssometimes** [comment]
> timer tick不是错误，我真正的错误是不能访问root文件夹的资源。改变root文件夹的权

> _No description provided._

你好，请问解决了吗

**Comment by qinguoyi** [comment]
如有空，建议贴下问题截图。timer tick是正常日志信息。
