### ISSUE TITLE
运行./server 9006 以后终端没有什么其他的反应，打开浏览器并不能连接上，Mysql也按Readme修改了

### ISSUE THREAD

**Issue by Jimmy063** [qinguoyi/TinyWebServer#53]
![image](https://user-images.githubusercontent.com/55016515/114505037-5adb9480-9c62-11eb-8f57-6a03b382cfc8.png)

![image](https://user-images.githubusercontent.com/55016515/114505075-6a5add80-9c62-11eb-8a3e-8313df30b401.png)

![image](https://user-images.githubusercontent.com/55016515/114505100-75ae0900-9c62-11eb-8ea1-90da2cb41b6a.png)

**Comment by 1462565291** [comment]
我也是这样，你是怎么解决的

**Comment by Jimmy063** [comment]
> 我也是这样，你是怎么解决的

确实是自己菜了，理解错项目里的Readme
//数据库登录名,密码,库名
string user = "root";
string passwd = "root";
string databasename = "yourdb";

这里user是用的root根用户，不用改的；password这个根据你登录MySQL数据库的密码填写；databasename 是你MySQL里面自己创建的一个数据库，我改完这个就对了

**Comment by 1462565291** [comment]
说不清楚，我觉得是我mysql版本不一样，我的是5.5，但是凭我14.04Ubuntu安装5.7.29，又让我痛不欲生。


---Original---
From: ***@***.***&gt;
Sent at: 2021年4月26日(Mon) AM10:27
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qinguoyi/TinyWebServer] 运行./server 9006 以后终端没有什么其他的反应，打开浏览器并不能连接上，Mysql也按Readme修改了 (#53)




  
我也是这样，你是怎么解决的
  
确实是自己菜了，理解错项目里的Readme
 //数据库登录名,密码,库名
 string user = "root";
 string passwd = "root";
 string databasename = "yourdb";
 
这里user是用的root根用户，不用改的；password这个根据你登录MySQL数据库的密码填写；databasename 是你MySQL里面自己创建的一个数据库，我改完这个就对了
 
&mdash;

**Comment by 1462565291** [comment]
你是可以跑了吗？

**Comment by 1462565291** [comment]
你是安装了 5.7.29 的mysql吗？

**Comment by Jimmy063** [comment]
是的我可以出来网页、图片之类的结果了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinguoyi/TinyWebServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinguoyi/TinyWebServer] 运行./server 9006 以后终端没有什么其他的反应，打开浏览器并不能连接上，Mysql也按Readme修改了 (#53)





 
你是可以跑了吗？

**Comment by 1462565291** [comment]
你加我 一下QQ，我方便聊一下 ， 我关注公众号，加好友没反应

**Comment by 1462565291** [comment]
1462565291

**Comment by Jimmy063** [comment]
5.7.33




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月26日(星期一) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 运行./server 9006 以后终端没有什么其他的反应，打开浏览器并不能连接上，Mysql也按Readme修改了 (#53)





 
你是安装了 5.7.29 的mysql吗？

**Comment by 1462565291** [comment]
你 ubuntu 版本多少

**Comment by 1462565291** [comment]
我源码编译安装，我真是头大

**Comment by Jimmy063** [comment]
我是18.04的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月26日(星期一) 上午10:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 运行./server 9006 以后终端没有什么其他的反应，打开浏览器并不能连接上，Mysql也按Readme修改了 (#53)





 
你 ubuntu 版本多少

**Comment by 1462565291** [comment]
你直接apt吗

**Comment by 1462565291** [comment]
你可以把配置好的 ubuntu 发我一份好吧

**Comment by Jimmy063** [comment]
对的全部是安装Readme上面的步骤做的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月26日(星期一) 上午10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 运行./server 9006 以后终端没有什么其他的反应，打开浏览器并不能连接上，Mysql也按Readme修改了 (#53)





 
你直接apt吗

**Comment by Jimmy063** [comment]
你就按照他的步骤去做是可以的，可能你就是mysql设置出了问题，你先安装好mysql，然后先试一下你的mysql能不能登上去、然后按照我说的把main函数修改一下，应该就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月26日(星期一) 上午10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 运行./server 9006 以后终端没有什么其他的反应，打开浏览器并不能连接上，Mysql也按Readme修改了 (#53)





 
你可以把配置好的 ubuntu 发我一份好吧

**Comment by 1462565291** [comment]
我版本的ubuntu  安装5.7的十分麻烦 ，我用5.5 的mysql 配置， 。/server 可以运行  日志也在记录 ，但是浏览器访问不了。 我现在就想 换一下mysql

**Comment by Jimmy063** [comment]
感觉还是按照他的配置要求吧，我也不清楚是不是mysql的版本问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月26日(星期一) 上午10:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 运行./server 9006 以后终端没有什么其他的反应，打开浏览器并不能连接上，Mysql也按Readme修改了 (#53)





 
我版本的ubuntu  安装5.7的十分麻烦 ，我用5.5 的mysql 配置， 。/server 可以运行  日志也在记录 ，但是浏览器访问不了。 我现在就想 换一下mysql

**Comment by 1462565291** [comment]
那我还得安装一个 16的Ubuntu ，还要配置， 感觉好麻烦，我先试试 ubuntu 5.7.19 看行不行

**Comment by 1462565291** [comment]
不对劲，如果实是自己菜了，理解错项目里的Readme
//数据库登录名,密码,库名
string user = "root";
string passwd = "root";
string databasename = "yourdb";

这里user是用的root根用户，不用改的；password这个根据你登录MySQL数据库的密码填写；databasename 是你MySQL里面自己创建的一个数据库，我改完这个就对了
如果是这个服务器都会运行不了，log 回报 MySQL error
，因为服务器都等不进去，你到底是什么原因，浏览器访问不了

**Comment by 1462565291** [comment]
![Uploading image.png…]()

**Comment by 1462565291** [comment]
![Uploading image.png…]()

**Comment by 1462565291** [comment]
![Uploading image.png…]()

**Comment by 1462565291** [comment]
原因还是没搞清楚，mysql  Ver 14.14 Distrib 5.7.19, for Linux (i686) using  EditLine wrapper

**Comment by 1462565291** [comment]
我 将 msql 换成 5.7 版本都不行，玩毛

**Comment by 1462565291** [comment]
你 将 浏览器访问 的页面 发我看看 ，你是如何访问成功的

**Comment by WYGNG** [comment]
感觉自己半天跑出来运气不错了

**Comment by 1462565291** [comment]
你有没有传文件的 版本 
我需要增加功能

**Comment by acg78219** [comment]
试一下在 ./server 之前加上 sudo，我是这么弄成功的

**Comment by handsomexiaoyifu** [comment]
> 

靠谱
