### ISSUE TITLE
修改main.c中的数据库初始化信息

### ISSUE THREAD

**Issue by ztms123** [qinguoyi/TinyWebServer#54]
修改main.c中的数据库初始化信息一直报错

**Comment by CharlesLG7580** [comment]
在虚拟机上可以跑，放到服务器上，centos的mysql永远连不上，总感觉前面数据库那几个信息配置的很有问题

**Comment by qinguoyi** [comment]
如有空，建议贴图看下具体报错。centos下有mysqlclient的报错是/usr/lib下so文件的问题，另外除了数据库配置信息，webserver.cpp下还有数据库的ip信息，localhost改为127.0.0.1即可
