### ISSUE TITLE
启动服务器后，Linux下的浏览器可以访问网页而Windows下不可以

### ISSUE THREAD

**Issue by fee1ng** [qinguoyi/TinyWebServer#55]
按照Readme的步骤启动服务器，Linux下浏览器可以访问127.0.0.1:9006而Windows下不可以
环境:Ubuntu 20.04虚拟机火狐浏览器
MySQL 8.0
Windows下为客户机谷歌浏览器

**Comment by WYGNG** [comment]
我这样搞也可以访问的呀,你是不是虚拟机桥接模式不通呀

**Comment by gokuson77** [comment]
> 我这样搞也可以访问的呀,你是不是虚拟机桥接模式不通呀

在windows访问的时候ip地址应该是多少呢

**Comment by wanziyu970127** [comment]
> > 我这样搞也可以访问的呀,你是不是虚拟机桥接模式不通呀
> 
> 在windows访问的时候ip地址应该是多少呢
好兄弟可以留个QQ嘛 交流一下呀

**Comment by pythoncjava9** [comment]
我也遇到了相同的问题，请问解决了吗？

> 按照Readme的步骤启动服务器，Linux下浏览器可以访问127.0.0.1:9006而Windows下不可以 环境:Ubuntu 20.04虚拟机火狐浏览器 MySQL 8.0 Windows下为客户机谷歌浏览器

**Comment by WYGNG** [comment]
没啥问题呀，当场就弄好了

**Comment by feifanxue** [comment]
看看linux里9006端口有没有放行：
firewall-cmd --zone=public --list-ports

永久放行9006端口：
firewall-cmd --zone=public --add-port=9006/tcp --permanent
firewall-cmd --reload
