### ISSUE TITLE
使用webbench测试，关掉日志文件，越测试性能越差，会出现 段错误(吐核) 问题，测到最后并发量为5时就出问题

### ISSUE THREAD

**Issue by darendehua** [qinguoyi/TinyWebServer#56]

**Comment by darendehua** [comment]
是server运行出现段错误（吐核）

**Comment by vcdlk** [comment]
可能是日志文件配置的时候的那几个参数设置的不正确，

**Comment by zhiyuanjiang** [comment]
同样碰到了这个问题，请问楼主解决这个问题了吗?

> g++ : 4.4.6
> os：centos6.3 4核8g
> 本地进行测试

**Comment by darendehua** [comment]
我改成reactor模型，然后增大线程池的线程数，就好了。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月20日(星期二) 中午1:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qinguoyi/TinyWebServer] 使用webbench测试，关掉日志文件，越测试性能越差，会出现 段错误(吐核) 问题，测到最后并发量为5时就出问题 (#56)




 
同样碰到了这个问题，请问楼主解决这个问题了吗?
  
g++ : 4.4.6
 os：centos6.3 4核8g
 本地进行测试

**Comment by zhiyuanjiang** [comment]
楼主知道是啥原因吗，我设置参数m=2也能处理上w的并发，但我实际测试服务端的连接数却只能达到100个连接左右，继续往上加client还是会出现段错误。

**Comment by darendehua** [comment]
我也不太清楚，我gdb看段错误的内容是因为内存越界，但是没找到哪里有越界。。。你实际测试的时候是一个一个的开了100个连接吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月20日(星期二) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qinguoyi/TinyWebServer] 使用webbench测试，关掉日志文件，越测试性能越差，会出现 段错误(吐核) 问题，测到最后并发量为5时就出问题 (#56)





 
楼主知道是啥原因吗，我设置参数m=2也能处理上w的并发，但我实际测试服务端的连接数却只能达到100个连接左右，继续往上加client还是会出现段错误。

**Comment by zhiyuanjiang** [comment]
用webbench，我把连接数打印到了日志里，删除和添加的时候都记录了。

**Comment by KeepStudyingAhead** [comment]
+1 +1，我也是遇到了这个问题，本来想关闭日志后进行压测，可是重新编译后一访问网页就是段错误（核心已转储）

**Comment by darendehua** [comment]
我是后来把它改成reactor模式，再把它放到云服务器上测试，压测就ok了


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月25日(星期六) 中午11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qinguoyi/TinyWebServer] 使用webbench测试，关掉日志文件，越测试性能越差，会出现 段错误(吐核) 问题，测到最后并发量为5时就出问题 (#56)




 
+1 +1，我也是遇到了这个问题，本来想关闭日志后进行压测，可是重新编译后一访问网页就是段错误（核心已转储）
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KeepStudyingAhead** [comment]
> 我是后来把它改成reactor模式，再把它放到云服务器上测试，压测就ok了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年9月25日(星期六) 中午11:15 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qinguoyi/TinyWebServer] 使用webbench测试，关掉日志文件，越测试性能越差，会出现 段错误(吐核) 问题，测到最后并发量为5时就出问题 (#56) +1 +1，我也是遇到了这个问题，本来想关闭日志后进行压测，可是重新编译后一访问网页就是段错误（核心已转储） — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

嗷嗷   我试试，我也有一个云服务器，本来想先在本地服务器上学明白了在上云的，既然你这么说，我直接上云试试吧，谢谢hxd！
