### ISSUE TITLE
到了./server这步，程序不运行，日志显示MySQL ERROR

### ISSUE THREAD

**Issue by langya19** [qinguoyi/TinyWebServer#58]
有没有小伙伴遇到这个问题呀，不会解决

**Comment by ssometimes** [comment]
你解决了吗，我也是这样的问题

**Comment by langya19** [comment]
你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月27日(星期二) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)

**Comment by ssometimes** [comment]
> 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年7月27日(星期二) 中午11:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)

我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下

**Comment by langya19** [comment]
> > 你好，没有解决，之前用的是云服务器，现在可以用虚拟机功能了 ------------------ 原始邮件 ---------- -------- _**@**_。_**> 发送时间：2021年7月27日（星期二）中午11:20 _**@**_ . **_>; _**@**_。_**_**@**_。**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR ( #58 )
> 
> 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。 如果你解决了，麻烦告诉下

没问题

**Comment by langya19** [comment]
> > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> 
> 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下

虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。

**Comment by langya19** [comment]
> > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> 
> 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下

虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。

**Comment by ssometimes** [comment]
> > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > 
> > 
> > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> 
> 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。

谢啦，那你云服务器的能实现吗

**Comment by langya19** [comment]
> > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > 
> > > 
> > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > 
> > 
> > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> 
> 谢啦，那你云服务器的能实现吗

还不行hh，就用虚拟机啦

**Comment by ssometimes** [comment]
> > > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > > 
> > > > 
> > > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > > 
> > > 
> > > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> > 
> > 
> > 谢啦，那你云服务器的能实现吗
> 
> 还不行hh，就用虚拟机啦

我重装成ubantu20和mysql8.0之后，虚拟机也成功了。感觉应该是因为mysql版本设置错误什么的吧。太难了，这几天一直在弄这个，都搞的怀疑人生了，真的谢谢，我后面再尝试下云服务器的，成功了再告诉你

**Comment by ssometimes** [comment]
> > > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > > 
> > > > 
> > > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > > 
> > > 
> > > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> > 
> > 
> > 谢啦，那你云服务器的能实现吗
> 
> 还不行hh，就用虚拟机啦


> > > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > > 
> > > > 
> > > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > > 
> > > 
> > > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> > 
> > 
> > 谢啦，那你云服务器的能实现吗
> 
> 还不行hh，就用虚拟机啦

我云服务器也是按虚拟机的配置重装后，能够运行了，端口有被监听到，也在阿里云打开安全组配置，但是外网访问不了，日志一直显示的是timer tick，感觉程序应该没问题，只是服务器网络访问这块有问题

**Comment by wwwWalker** [comment]
> > > > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > > > 
> > > > > 
> > > > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > > > 
> > > > 
> > > > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > > > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> > > 
> > > 
> > > 谢啦，那你云服务器的能实现吗
> > 
> > 
> > 还不行hh，就用虚拟机啦
> 
> > > > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > > > 
> > > > > 
> > > > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > > > 
> > > > 
> > > > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > > > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> > > 
> > > 
> > > 谢啦，那你云服务器的能实现吗
> > 
> > 
> > 还不行hh，就用虚拟机啦
> 
> 我云服务器也是按虚拟机的配置重装后，能够运行了，端口有被监听到，也在阿里云打开安全组配置，但是外网访问不了，日志一直显示的是timer tick，感觉程序应该没问题，只是服务器网络访问这块有问题

你好,我也是问题,请问现在解决了吗,如果解决了,可以告诉我具体解决措施吗?

**Comment by ssometimes** [comment]
> > > > > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > > > > 
> > > > > > 
> > > > > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > > > > 
> > > > > 
> > > > > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > > > > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> > > > 
> > > > 
> > > > 谢啦，那你云服务器的能实现吗
> > > 
> > > 
> > > 还不行hh，就用虚拟机啦
> > 
> > 
> > > > > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > > > > 
> > > > > > 
> > > > > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > > > > 
> > > > > 
> > > > > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > > > > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> > > > 
> > > > 
> > > > 谢啦，那你云服务器的能实现吗
> > > 
> > > 
> > > 还不行hh，就用虚拟机啦
> > 
> > 
> > 我云服务器也是按虚拟机的配置重装后，能够运行了，端口有被监听到，也在阿里云打开安全组配置，但是外网访问不了，日志一直显示的是timer tick，感觉程序应该没问题，只是服务器网络访问这块有问题
> 
> 你好,我也是问题,请问现在解决了吗,如果解决了,可以告诉我具体解决措施吗?

添加安全组配置后，你要在你阿里云那里点开你的服务器，有一个防火墙的选项，要添加你的端口在里面，不然会被拒绝访问。如果还不行的话，阿里云说ubantu会默认关掉端口，你在系统里面打开这个端口

**Comment by wwwWalker** [comment]
你好,我是本地直接装得Ubuntu20.04 , Mysql8.0,按照Readme做了之MYSQL ERROR 这了 . 
就是数据库连不上~
















在 2021-08-04 09:41:41，"ssometimes" ***@***.***> 写道：

你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ @.> 发送时间: 2021年7月27日(星期二) 中午11:20 _@**._>; ***@***.***@.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)

我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下

虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。

谢啦，那你云服务器的能实现吗

还不行hh，就用虚拟机啦

你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ @.> 发送时间: 2021年7月27日(星期二) 中午11:20 _@**._>; ***@***.***@.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)

我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下

虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。

谢啦，那你云服务器的能实现吗

还不行hh，就用虚拟机啦

我云服务器也是按虚拟机的配置重装后，能够运行了，端口有被监听到，也在阿里云打开安全组配置，但是外网访问不了，日志一直显示的是timer tick，感觉程序应该没问题，只是服务器网络访问这块有问题

你好,我也是问题,请问现在解决了吗,如果解决了,可以告诉我具体解决措施吗?

添加安全组配置后，你要在你阿里云那里点开你的服务器，有一个防火墙的选项，要添加你的端口在里面，不然会被拒绝访问。如果还不行的话，阿里云说ubantu会默认关掉端口，你在系统里面打开这个端口

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ssometimes** [comment]
> 你好,我是本地直接装得Ubuntu20.04 , Mysql8.0,按照Readme做了之MYSQL ERROR 这了 . 就是数据库连不上~ 在 2021-08-04 09:41:41，"ssometimes" ***@***.***> 写道： 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ @.> 发送时间: 2021年7月27日(星期二) 中午11:20 _@**._>; ***@***.***@.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58) 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。 谢啦，那你云服务器的能实现吗 还不行hh，就用虚拟机啦 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ @.> 发送时间: 2021年7月27日(星期二) 中午11:20 _@**._>; ***@***.***@.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58) 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。 谢啦，那你云服务器的能实现吗 还不行hh，就用虚拟机啦 我云服务器也是按虚拟机的配置重装后，能够运行了，端口有被监听到，也在阿里云打开安全组配置，但是外网访问不了，日志一直显示的是timer tick，感觉程序应该没问题，只是服务器网络访问这块有问题 你好,我也是问题,请问现在解决了吗,如果解决了,可以告诉我具体解决措施吗? 添加安全组配置后，你要在你阿里云那里点开你的服务器，有一个防火墙的选项，要添加你的端口在里面，不然会被拒绝访问。如果还不行的话，阿里云说ubantu会默认关掉端口，你在系统里面打开这个端口 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

可能是你的mysql装的有问题吧，我之前是mysql5.7一直不行，然后换了版本也换了不同的安装方法，然后就成功了。或者你尝试重启下mysql，按照上面老哥说的免密登陆。

**Comment by qinguoyi** [comment]
> > > > > > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > > > > > 
> > > > > > 
> > > > > > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> > > > > 
> > > > > 
> > > > > 虚拟机版本ubuntu20.04, mysql版本8.0， 按照README做，成功访问。
> > > > > 我service mysql stop后，再次 ./server，又出现了原问题，遂将mysql登录密码设置成了skip-grant-tables，也就是免密登录，重启mysql后./server，浏览器能正常访问。
> > > > 
> > > > 
> > > > 谢啦，那你云服务器的能实现吗
> > > 
> > > 
> > > 还不行hh，就用虚拟机啦
> > 
> > 
> > 我重装成ubantu20和mysql8.0之后，虚拟机也成功了。感觉应该是因为mysql版本设置错误什么的吧。太难了，这几天一直在弄这个，都搞的怀疑人生了，真的谢谢，我后面再尝试下云服务器的，成功了再告诉你
> 
> Ubuntu20.04 MySQL8.0 为啥我一直报错timer tick?大佬你们怎么弄得呀，救命 <img alt="image" width="1280" src="https://user-images.githubusercontent.com/26659248/163194844-319dc01c-133f-42a4-88a6-59646185ab8f.png">
> 
> > > 你好，没有解决，之前用的是云服务器，现在打算用虚拟机试试 ------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年7月27日(星期二) 中午11:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qinguoyi/TinyWebServer] 到了./server这步，程序不运行，日志显示MySQL ERROR (#58)
> > 
> > 
> > 我一开始也是用的阿里云，今天用虚拟机试了一下，还是一样的问题。如果你后面解决了，麻烦告诉下
> 
> 你们运行sh ./build.sh后有warn吗？是不是我没编译好呀？

warning的没有处理，只要不是error就行(逃
