### ISSUE TITLE
请问数据库安装好后,也创建了表. 根据Readme运行后没有报错,但后面该如何做不知道了

### ISSUE THREAD

**Issue by YuQi9797** [qinguoyi/TinyWebServer#61]
请问下,Readme步骤都没错.  我现在是浏览器输入什么内容 实现 前后端运行效果呀?   localhost 和 端口号 是根据什么进行设置的 还是啥? 有人知道吗?

**Comment by acg78219** [comment]
127.0.0.1：9006
