### ISSUE TITLE
运行./server 报错：段错误 (核心已转储)

### ISSUE THREAD

**Issue by newlzy** [qinguoyi/TinyWebServer#66]
![3SF}S2UGI4)L()UE_Q@`2A7](https://user-images.githubusercontent.com/40860759/129869560-83ca307d-791a-4e03-aebb-b3ca41a4115a.png)

请问怎么才能联系到你？

**Comment by gokuson77** [comment]
你可以调式一下core文件，查看问题出在哪。
先执行ulimit -c unlimited，然后执行 gdb ./server core

**Comment by LCLxiaolou** [comment]
楼上正解。我的是因为数据库改的时候改错了，多检查一下，代码没有问题

**Comment by yangA7S** [comment]
> 楼上正解。我的是因为数据库改的时候改错了，多检查一下，代码没有问题

盲猜是把局部变量地址push到连接队列里了

**Comment by KydoChen** [comment]
看下log，如果是select error有可能是本地文件和你数据库的table有字段不对应

**Comment by qinguoyi** [comment]
ServerLog是用来尽快定位问题的，有问题可以先看log输出

**Comment by facesin** [comment]
> 

哥们儿，这个问题解决了没，我和你同样的问题

**Comment by facesin** [comment]
> ![3SF}S2UGI4）L（）UE_Q@'2A7](https://user-images.githubusercontent.com/40860759/129869560-83ca307d-791a-4e03-aebb-b3ca41a4115a.png)
> 
> 请问怎么才能联系到你？

哥们儿，问一下问题解决了没，我和你一样的问题
