### ISSUE TITLE
服务器能运行，端口已打开，并且终端输出了连接信息，但浏览器端就是加载不出来页面

### ISSUE THREAD

**Issue by JasmineChan0831** [qinguoyi/TinyWebServer#73]
![image](https://user-images.githubusercontent.com/37476138/135024144-872c9eee-af45-458f-820e-a64d97e9c01d.png)
![image](https://user-images.githubusercontent.com/37476138/135024207-4fa2b558-1a1a-4cfd-a8bb-cd02cf083948.png)

**Comment by JasmineChan0831** [comment]
已解决。记录一下遇到的困难和解决方法。
这种连接上了又没加载出来，经过一步步debug发现是连接mysql的时候“localhost”会导致失败，把它改成"127.0.0.1"可以成功解决。
nc -lk 9007
打开端口
netstat -an | grep 9007
查看是否打开了端口，没输出就是关闭状态

**Comment by czy1805209120** [comment]
求助！老哥我也显示不了页面啊，你说的这个localhost是在mysql改吗 ？ 怎么改？求看到回复

**Comment by qinguoyi** [comment]
> 求助！老哥我也显示不了页面啊，你说的这个localhost是在mysql改吗 ？ 怎么改？求看到回复

在webserver.cpp里有数据库的连接api，里面有db的ip地址
