### ISSUE TITLE
为什么url中'/'后面会有1 2 3 4 5 6 7这些数字呢

### ISSUE THREAD

**Issue by duanchao1019** [qinguoyi/TinyWebServer#74]
看代码里通过url中第一个'/'后面的数字来判断用户请求的是什么页面，请问这些数字是怎么来的呢

**Comment by LeoShawn-0816** [comment]
> 



> 看代码里通过url中第一个'/'后面的数字来判断用户请求的是什么页面，请问这些数字是怎么来的呢

root文件夹下的html的代码中会有这些数字，
比如：judge.html文件中第13行代码<form action="0" method="post">
可以看一下HTML相关的代码

**Comment by LeoShawn-0816** [comment]
> 看代码里通过url中第一个'/'后面的数字来判断用户请求的是什么页面，请问这些数字是怎么来的呢

root文件夹下的html的代码中会有这些数字，
比如：judge.html文件中第13行代码<form action="0" method="post">
可以看一下HTML相关的代码

**Comment by LeoShawn-0816** [comment]
> 看代码里通过url中第一个'/'后面的数字来判断用户请求的是什么页面，请问这些数字是怎么来的呢

root文件夹下的judge.html文件的第13行代码`<form action="0" method="post">`
可以看一下HTML的相关内容

**Comment by qinguoyi** [comment]
这些数据没有实际意义，类似路由跳转
