### ISSUE TITLE
请问如何重现README里面的QPS测试？服务机器与测试机器需要分离，且放在同一个内网吗？

### ISSUE THREAD

**Issue by JaxChan25** [qinguoyi/TinyWebServer#77]
问题表现：QPS无法上万
问题出现：server和测试放在同一个机器，机器是2核4GB内存。用webbench 测试，webbench -c 8000 -t 5 下QPS只能达到6000左右，甚至不上万。
请求解决：如何复现近十万的QPS

感谢回复。

**Comment by czy1805209120** [comment]
老哥，我小白，代码编译都通过了，我是直接在本地的虚拟机的firefox访问服务器的，这样可以吗？我可能有一些步骤做错了 或者忽略了一些步骤，我想问一下你的操作步骤是怎样的，求回复，小生感激不尽。
![image](https://user-images.githubusercontent.com/96863496/153704906-797c0170-7cc4-428f-83f8-9f9580a3cabb.png)

**Comment by InternetofThingsprogrammer** [comment]
> 问题表现：QPS无法上万 问题出现：server和测试放在同一个机器，机器是2核4GB内存。用webbench 测试，webbench -c 8000 -t 5 下QPS只能达到6000左右，甚至不上万。 请求解决：如何复现近十万的QPS
> 
> 感谢回复。

我也是按照文档的参数只有一万左右的qps,我给了12核心,不知道怎么回事莫非12代i5负优化?

**Comment by xiaochao97-github** [comment]
我也无法实现QPS破万，我自己的服务器也是2核4G的，我的QPS只有：Speed=67800 pages/min, 126672 bytes/sec，1100多一点，太低了，怎么解决啊

**Comment by qinguoyi** [comment]
> 我也无法实现QPS破万，我自己的服务器也是2核4G的，我的QPS只有：Speed=67800 pages/min, 126672 bytes/sec，1100多一点，太低了，怎么解决啊

硬件性能比较差，和代码无关哈，项目中的压测环境是8c+16g
