### ISSUE TITLE
A nullptr can lead to `Segmentation fault`

### ISSUE THREAD

**Issue by lanqsh** [qinguoyi/TinyWebServer#79]
https://github.com/qinguoyi/TinyWebServer/blob/7e103e82375d316403dbc0ea25d2feca7a2146b6/http/http_conn.cpp?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L24

if mysql connect err,will this ptr be NULL?
fix it will be great
 
![image](https://user-images.githubusercontent.com/12372700/138673377-2ed9049d-6892-4237-bdcb-981a5a7fcf00.png)

**Comment by qinguoyi** [comment]
之前做的时候，异常情况考虑的比较少。如有空，可以提交下mr，tks
