### ISSUE TITLE
webbench测试设置什么参数比较好，一般什么标准测试的结果就算好的了

### ISSUE THREAD

**Issue by Feny321** [qinguoyi/TinyWebServer#82]
客户端一般设置多少，我设置一万多，直接失败了。访问成功的数又表示什么呢？设置五秒内访问和一分钟内访问有什么区别？

**Comment by 2900322208** [comment]
大佬，在云服务器上跑的话需要修改代码里的那些部分

**Comment by xiaochao97-github** [comment]
想知道社长测试的服务器配置是什么？我的云服务器是2核4G，最大也就支持8000多的并发，而且qps只能到1000多，实在太烂了

**Comment by qinguoyi** [comment]
i7 8c+16g ssd
