### ISSUE TITLE
3CGISQL.cgi和2CGISQL.cgi在哪里

### ISSUE THREAD

**Issue by Feny321** [qinguoyi/TinyWebServer#83]

**Comment by Feny321** [comment]
知道了，在do_request里就处理了

**Comment by wuyusi1** [comment]
请问do_request在哪里呀

**Comment by cyjiayou** [comment]
> 知道了，在do_request里就处理了

这部分我有点不清楚，想问问你
假如现在是注册检验，没有找到同名的时候，这里是将 url 进行了处理，m_real_file 的地址按我的理解还是 *.cgi 路径，此时文件打不开不是应该会出错吗，为什么这里会自动跳转

**Comment by qinguoyi** [comment]
可以看下http_conn::HTTP_CODE http_conn::parse_request_line里的处理

**Comment by jeffreyyyyyyyyy** [comment]
您好，这里cgi也是没看懂，3CGISQL.cgi，2CGISQL.cgi这些cgi脚本在哪里啊 do_request这里只是判断了cgi变量是否等于1，然后判断用户密码，但是感觉完全跟cgi没啥关系啊？最主要这些cgi脚本文件在哪里啊怎么完全找不到

**Comment by Cyjiayou** [comment]
> 您好，这里cgi也是没看懂，3CGISQL.cgi，2CGISQL.cgi这些cgi脚本在哪里啊 do_request这里只是判断了cgi变量是否等于1，然后判断用户密码，但是感觉完全跟cgi没啥关系啊？最主要这些cgi脚本文件在哪里啊怎么完全找不到

很久之前看的了，这里的逻辑是没有问题的，不需要管cgi文件，在逻辑中实现了跳转的功能，请仔细查看代码，或者debug一下
