### ISSUE TITLE
./server -p 9006显示server: webserver.cpp:131: void WebServer::eventListen(): Assertion `ret >= 0' failed.

### ISSUE THREAD

**Issue by PeggieWu** [qinguoyi/TinyWebServer#86]
![image](https://user-images.githubusercontent.com/41352298/143671026-1a0af904-8c4e-4046-84f7-47c607e48e95.png)

**Comment by PeggieWu** [comment]
折腾两天了，求教

**Comment by TJ-LT** [comment]
同样的问题，楼主解决了吗？

**Comment by Young-Flash** [comment]
检查一下9006端口是否被占用了

**Comment by PeggieWu** [comment]
换成Ubuntu18，MySQL5.7已经解决了，给大家一个参考~

**Comment by zkzk123zk** [comment]
楼上说的很对，主要是端口9006被占用了，你可以使用其他的端口，例如"./server -p 9007"
