### ISSUE TITLE
服务器能正常监听端口，但是浏览器不显示http应答的文件

### ISSUE THREAD

**Issue by DJKarlHarris** [qinguoyi/TinyWebServer#91]
![image](https://user-images.githubusercontent.com/78162333/147403807-547719f4-9072-437f-9577-bf446d05056a.png)

Log文件:
![image](https://user-images.githubusercontent.com/78162333/147403819-1e354ceb-8596-4221-a8b4-90aa71309fd6.png)

**Comment by DJKarlHarris** [comment]
解决了，是代码出了问题，重新换了一份上去

**Comment by czy1805209120** [comment]
老哥我新手，代码都可以编译通过，但是浏览器不能访问服务器，你的访问操作流程可以说一说吗？
![image](https://user-images.githubusercontent.com/96863496/153704562-54deccca-1cd9-4741-8b76-5fa64cd78add.png)

**Comment by DJKarlHarris** [comment]
你检查一下mysql是否安装正常

**Comment by DJKarlHarris** [comment]
`./server -p xxx`
要指定端口号

**Comment by qinguoyi** [comment]
> > 老哥我新手，代码都可以编译通过，但是浏览器不能访问服务器，你的访问操作流程可以说一说吗？
> > ![image](https://user-images.githubusercontent.com/96863496/153704678-8dfc7920-8d41-4575-8534-88f59bea1f39.png)
> 
> 解决了吗?我也服务端正常运行，浏览器访问不了

这种没有hung住的输出，一般是运行问题，看下日志呢
