### ISSUE TITLE
怎么退出服务器...

### ISSUE THREAD

**Issue by MatchaSoda** [qinguoyi/TinyWebServer#97]
只会关掉终端来关闭服务器。
好像看到循环收到SIGTERM信号便跳出。怎么发送这个信号呢？
搜了一下是用kill，但是不太会用。./server之后也不能输入了。

**Comment by Mend0s** [comment]
你会退出了没

**Comment by MatchaSoda** [comment]
>

**Comment by MatchaSoda** [comment]
> 你会退出了没

会了但是没完全会。
可以在其他终端用"ps -ef | grep ./server"来查找进程id，然后用"kill -15 进程id"来发送SIGTERM信号。
另外，"kill -9 进程id"是强制关闭，在当前终端按 Ctrl + c 也可以。
大概是这样吧

**Comment by Mend0s** [comment]
> > 你会退出了没
> 
> 会了但是没完全会。 可以在其他终端用"ps -ef | grep ./server"来查找进程id，然后用"kill -15 进程id"来发送SIGTERM信号。 另外，"kill -9 进程id"是强制关闭，在当前终端按 Ctrl + c 也可以。 大概是这样吧



> > 你会退出了没
> 
> 会了但是没完全会。 可以在其他终端用"ps -ef | grep ./server"来查找进程id，然后用"kill -15 进程id"来发送SIGTERM信号。 另外，"kill -9 进程id"是强制关闭，在当前终端按 Ctrl + c 也可以。 大概是这样吧

直接重启好像也可以我刚发现

**Comment by Mend0s** [comment]
朋友你会用公网ip登录吗，我现在只能用127.0.0.1登录，而且Ubuntu之外的浏览器连127.0.0.1都登不了

**Comment by MatchaSoda** [comment]
> 朋友你会用公网ip登录吗，我现在只能用127.0.0.1登录，而且Ubuntu之外的浏览器连127.0.0.1都登不了

还没弄懂，我也都是在本地运行的。127.0.0.1是本地ip的意思，其他设备肯定不能用这个连，如果你用的虚拟机，可以查下虚拟机的ip，再不行再看看防火墙什么的。我也不是很清楚。

**Comment by Mend0s** [comment]
> > 朋友你会用公网ip登录吗，我现在只能用127.0.0.1登录，而且Ubuntu之外的浏览器连127.0.0.1都登不了
> 
> 还没弄懂，我也都是在本地运行的。127.0.0.1是本地ip的意思，其他设备肯定不能用这个连，如果你用的虚拟机，可以查下虚拟机的ip，再不行再看看防火墙什么的。我也不是很清楚。

好的谢谢

**Comment by Mend0s** [comment]
> > 朋友你会用公网ip登录吗，我现在只能用127.0.0.1登录，而且Ubuntu之外的浏览器连127.0.0.1都登不了
> 
> 还没弄懂，我也都是在本地运行的。127.0.0.1是本地ip的意思，其他设备肯定不能用这个连，如果你用的虚拟机，可以查下虚拟机的ip，再不行再看看防火墙什么的。我也不是很清楚。

朋友我弄出来了，这一套如果在云服务器上做，用用云服务器的ip端口就能上，谢谢你昨天提醒到我了，现在阿里云38r一年应该够用

**Comment by 2900322208** [comment]
> > > 朋友你会用公网ip登录吗，我现在只能用127.0.0.1登录，而且Ubuntu之外的浏览器连127.0.0.1都登不了
> > 
> > 
> > 还没弄懂，我也都是在本地运行的。127.0.0.1是本地ip的意思，其他设备肯定不能用这个连，如果你用的虚拟机，可以查下虚拟机的ip，再不行再看看防火墙什么的。我也不是很清楚。
> 
> 朋友我弄出来了，这一套如果在云服务器上做，用用云服务器的ip端口就能上，谢谢你昨天提醒到我了，现在阿里云38r一年应该够用

在云服务器上跑需要修改那些部分 我改了他说的快速运行里的数据库那部分 为啥启动不了
